# ===========================
# Docker Compose - Desenvolvimento
# ===========================

version: '3.8'

services:
  # ===========================
  # Aplicação - Modo Desenvolvimento
  # ===========================
  hackathon-api-dev:
    container_name: hackathon-api-dev
    image: hackathon-api:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: build # Para debugging
    ports:
      - "5000:8080"    # HTTP
      - "5001:8081"    # HTTPS (se configurado)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__LocalDb=/app/data/hack.db
    volumes:
      - hackathon-data-dev:/app/data
      - ./Hackathon.API/appsettings.Development.json:/app/appsettings.Development.json:ro
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - hackathon-dev-network
    depends_on:
      hackathon-db-dev:
        condition: service_healthy

  # ===========================
  # Banco de Dados - Desenvolvimento
  # ===========================
  hackathon-db-dev:
    container_name: hackathon-db-dev
    image: alpine:3.19
    command: |
      sh -c "
        mkdir -p /data &&
        touch /data/hack.db &&
        chmod 666 /data/hack.db &&
        echo 'Banco SQLite (DEV) inicializado' &&
        tail -f /dev/null
      "
    volumes:
      - hackathon-data-dev:/data
    healthcheck:
      test: ["CMD", "test", "-f", "/data/hack.db"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - hackathon-dev-network

# ===========================
# Volumes - Desenvolvimento
# ===========================
volumes:
  hackathon-data-dev:
    driver: local
    name: hackathon-data-dev

# ===========================
# Rede - Desenvolvimento
# ===========================
networks:
  hackathon-dev-network:
    driver: bridge
    name: hackathon-dev-network
