// <auto-generated />
using System;
using Hackathon.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hackathon.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250821205640_AlterMetricas")]
    partial class AlterMetricas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Hackathon.Domain.Entities.MetricaRequisicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_HORA");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("TX_ENDPOINT");

                    b.Property<string>("NomeApi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_API");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NU_STATUS_CODE");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FL_SUCESSO");

                    b.Property<long>("TempoRespostaMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NU_TEMPO_RESPOSTA_MS");

                    b.HasKey("Id");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("IX_METRICA_DT_HORA");

                    b.HasIndex("NomeApi", "DataHora")
                        .HasDatabaseName("IX_METRICA_API_DATA");

                    b.ToTable("METRICA_REQUISICAO", (string)null);
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.Parcela", b =>
                {
                    b.Property<Guid>("IdResultado")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID_RESULTADO");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NU_PARCELA");

                    b.Property<decimal>("ValorAmortizacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VR_AMORTIZACAO");

                    b.Property<decimal>("ValorJuros")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VR_JUROS");

                    b.Property<decimal>("ValorPrestacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VR_PRESTACAO");

                    b.HasKey("IdResultado", "Numero");

                    b.HasIndex("Numero")
                        .HasDatabaseName("IX_PARCELA_NU_PARCELA");

                    b.ToTable("PARCELA", (string)null);
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.ResultadoSimulacao", b =>
                {
                    b.Property<Guid>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ID_RESULTADO");

                    b.Property<Guid>("IdSimulacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID_SIMULACAO");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TP_SISTEMA_AMORTIZACAO");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VR_TOTAL");

                    b.HasKey("IdResultado");

                    b.HasIndex("IdSimulacao")
                        .HasDatabaseName("IX_RESULTADO_SIMULACAO_ID_SIMULACAO");

                    b.ToTable("RESULTADO_SIMULACAO", (string)null);
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.Simulacao", b =>
                {
                    b.Property<Guid>("IdSimulacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ID_SIMULACAO");

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CO_PRODUTO");

                    b.Property<DateOnly>("DataReferencia")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_REFERENCIA");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_PRODUTO");

                    b.Property<string>("EnvelopJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_ENVELOP_JSON");

                    b.Property<short>("PrazoMeses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NU_PRAZO_MESES");

                    b.Property<decimal>("TaxaJuros")
                        .HasColumnType("decimal(10,9)")
                        .HasColumnName("PC_TAXA_JUROS");

                    b.Property<decimal>("ValorDesejado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VR_DESEJADO");

                    b.HasKey("IdSimulacao");

                    b.HasIndex("CodigoProduto")
                        .HasDatabaseName("IX_SIMULACAO_CO_PRODUTO");

                    b.HasIndex("DataReferencia")
                        .HasDatabaseName("IX_SIMULACAO_DT_REFERENCIA");

                    b.ToTable("SIMULACAO", (string)null);
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("Hackathon.Domain.Entities.ResultadoSimulacao", "Resultado")
                        .WithMany("Parcelas")
                        .HasForeignKey("IdResultado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.ResultadoSimulacao", b =>
                {
                    b.HasOne("Hackathon.Domain.Entities.Simulacao", "Simulacao")
                        .WithMany("Resultados")
                        .HasForeignKey("IdSimulacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.ResultadoSimulacao", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.Simulacao", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
